#!/bin/bash -l
#SBATCH --job-name="poisson_HYBRID"
#SBATCH --account="uzh8"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=6
#SBATCH --cpus-per-task=6
#SBATCH --partition=debug
#SBATCH --constraint=mc
##SBATCH --hint=nomultithread
#SBATCH --output=out_poisson_HYBRID_6_6.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MPICH_MAX_THREAD_SAFETY=single
srun main
