#!/bin/bash -l
#SBATCH --job-name="cpi_serial_extern_gettime"
#SBATCH --account="uzg2"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread
#SBATCH --output=cpi_serial_extern_gettime.log
#SBATCH --error=cpi_serial_extern_gettime.error

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun cpi
